title: Coding Courses @ University of Helsinki
logo: /assets/img/Logo.png
description: This is a site for collecting coding courses in the University of Helsinki.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
navbar-img: "favicon.png"
future: true
